version: '3'

services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
